### ISSUE TITLE
Help needed with R

### ISSUE THREAD

**Issue by meerab1** [trr266/rescorptrans#6]
Hi,
I am not able to build on Rstudio and I am stuck with that. I did follow all the procedures shown in youtube videos of how to install R, GIT and clone repository. I installed packages before running it. It is giving me following error:
'\lipasto\kotidir04$\mabdia\My Documents\ResCorpTrans\trer'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported. Defaulting to Windows directory.
make: *** No targets specified and no makefile found. Stop.

Exited with status 2.

Can anyone help me with that?

**Comment by joachim-gassen** [comment]
Hmm... this looks as if you are operating with Windows and from inside a network share that is not mounted to a disk drive. Can you move the trer folder to your or local hard disk? Or map your network folder to a network drive?

See https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-10-29ce55d1-34e3-a7e2-4801-131475f9557d

**Comment by meerab1** [comment]
Thank you for the help. It did not work, but I installed Rstudio in another computer and it is working fine now.

**Comment by meerab1** [comment]
Thank you for quick response and help. I tried mapping network folder but it still did not work. But your comment helped me understand the problem, so I just installed RStudio in another computer and it is working fine now. Thank you once again.

**Comment by joachim-gassen** [comment]
Perfect. Closing this issue as it seems to be related mostly to your local environment.
